from local_config import Settings

SQLALCHEMY_DATABASE_URI = 'sqlite:///../database.sqlite'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = Settings.SECRET_KEY
SECURITY_PASSWORD_SALT = Settings.SECURITY_PASSWORD_SALT
SECURITY_REGISTERABLE = True
SECURITY_RECOVERABLE = True
SECURITY_CHANGEABLE = False
SECURITY_CONFIRMABLE = True

SECURITY_EMAIL_SENDER = Settings.MAIL_USERNAME
SECURITY_SEND_REGISTER_EMAIL = True
FLASK_ADMIN_SWATCH = 'cerulean'

MAIL_SERVER = 'smtp.web.de'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = Settings.MAIL_USERNAME
MAIL_PASSWORD = Settings.MAIL_PASSWORD

# Convert feature - Dropzone
UPLOAD_PATH = 'uploads'
DROPZONE_MAX_FILE_SIZE = 200
DROPZONE_ALLOWED_FILE_TYPE = 'audio'
