import os

from local_config import Settings

SQLALCHEMY_DATABASE_URI = 'sqlite:///../database.sqlite'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = Settings.SECRET_KEY
SECURITY_PASSWORD_SALT = Settings.SECURITY_PASSWORD_SALT
SECURITY_REGISTERABLE = True
SECURITY_RECOVERABLE = True
SECURITY_CHANGEABLE = False
SECURITY_CONFIRMABLE = True
SECURITY_BLUEPRINT_NAME = 'multilingual'

SECURITY_EMAIL_SENDER = Settings.MAIL_USERNAME
SECURITY_SEND_REGISTER_EMAIL = True
SEND_PASSWORD_RESET_EMAIL = True
FLASK_ADMIN_SWATCH = 'cerulean'

MAIL_SERVER = 'smtp.web.de'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = Settings.MAIL_USERNAME
MAIL_PASSWORD = Settings.MAIL_PASSWORD

# Babel
LANGUAGES = ['en', 'de']

# Convert feature - Dropzone
UPLOAD_PATH = os.getcwd() + '/uploads'
DROPZONE_MAX_FILE_SIZE = 200
DROPZONE_ALLOWED_FILE_CUSTOM = True
DROPZONE_ALLOWED_FILE_TYPE = '.mp3'
DROPZONE_TIMEOUT = 5*60*1000
