SQLALCHEMY_DATABASE_URI = 'sqlite:///../database.sqlite'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = 'secretkey'
SECURITY_PASSWORD_SALT = 'secretsalt'
SECURITY_REGISTERABLE = True
SECURITY_RECOVERABLE = True
SECURITY_CHANGEABLE = False
SECURITY_CONFIRMABLE = True

SECURITY_EMAIL_SENDER = 'email-adress@example.com'
SECURITY_SEND_REGISTER_EMAIL = True
FLASK_ADMIN_SWATCH = 'cerulean'


MAIL_SERVER = 'smtp.example.com'
MAIL_PORT = 465
MAIL_USE_SSL = True
MAIL_USERNAME = 'email-adress@example.com'
MAIL_PASSWORD = 'password'
