SQLALCHEMY_DATABASE_URI = 'sqlite:///../database.sqlite'
GALLERY_UPLOAD_DIR = '/folder/to/uploads'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECRET_KEY = 'secretkey'
SECURITY_PASSWORD_SALT = 'secretsalt'
SECURITY_REGISTERABLE = True
SECURITY_SEND_REGISTER_EMAIL = False
FLASK_ADMIN_SWATCH = 'cerulean'

# Babel
LANGUAGES = ['en', 'de']
