version: "3.9"  # optional since v1.27.0
services:
  dev:
    build:
      context: ..
      dockerfile: ./.docker/dev.Dockerfile
    image: audio_converter:dev
    ports:
      - "5000:5000"
    volumes:
      - "..:./app"
  prod:
    build:
      context: ..
      dockerfile: ./.docker/prod.Dockerfile
    image: audio_converter:latest
    volumes:
      - "..:./app"
