version: "3.9"

services:
  dev:
    container_name: audio-converter_dev
    build:
      context: ..
      dockerfile: ./.docker/dev.Dockerfile
    image: audio_converter:dev
    environment:
      - TZ=Europe/Berlin
    volumes:
      - "..:/app:rw"
      - "../media:/app/media:rw"
    ports:
      - "5000:5000"

  prod:
    container_name: audio-converter_prod
    build:
      context: ..
      dockerfile: ./.docker/prod.Dockerfile
    image: audio_converter:latest
    environment:
      - TZ=Europe/Berlin
    volumes:
      - "../media:/app/media:rw"
    ports:
      - "8080:8080"
