name: Deploy audio-converter image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  USER_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  IMAGE_NAME: audio-converter

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Satisfy dependencies
        run: apt install -y curl jq
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set up docker
        uses: docker/setup-buildx-action@v1
      - name: Log in to docker hub
        run: docker login --username=$USER_NAME --password=$PASSWORD
      - name: Get release tag
        run: echo "RELEASE_TAG=$(curl https://api.github.com/repos/mac641/audio-converter/releases/latest -s | jq .name -r)" >> $GITHUB_ENV
      - name: Get current branch
        run: git fetch && echo "CURRENT_BRANCH=$(git branch --show-current)" >> $GITHUB_ENV
      - name: Generate image tag
        run: >-
          if [ "${{ env.CURRENT_BRANCH }}" == "main" ]; then
            echo "IMAGE_TAG=$USER_NAME/$IMAGE_NAME:${{ env.RELEASE_TAG }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=$USER_NAME/$IMAGE_NAME:dev" >> $GITHUB_ENV
          fi
      - name: Build image
        run: docker build -f .docker/prod.Dockerfile -t ${{ env.IMAGE_TAG }} .
      - name: Push image to docker hub
        run: docker push ${{ env.IMAGE_TAG }}
      - name: Tag built image as latest and push it to docker hub if not dev
        run: >-
          if [[ "${{ env.IMAGE_TAG }}" != *"dev"* ]]; then
            docker image tag ${{ env.IMAGE_TAG }} $USER_NAME/$IMAGE_NAME:latest
            docker push $USER_NAME/$IMAGE_NAME:latest
          fi
